### ISSUE TITLE
Hypercooler mixing nitrogen + liquid nitrogen in same pipe

### ISSUE THREAD

**Issue by xaviershay** [PreLeyZero/exotic-industries#17]
With a nitrogen air filter piped straight into a hypercooler for liquid nitrogen, I get regular nitrogen showing up in the pipe on the left (where I would expect only liquid)

![20230416184322_1](https://user-images.githubusercontent.com/1714/232287464-e63f1844-94fe-49dd-a8a2-699d730b4809.jpg)

This is what the hypercooler looks like. (Is it having two outputs causing something weird?)

![20230416184331_1](https://user-images.githubusercontent.com/1714/232287520-6f18f5e3-e72c-4cc1-b1d5-5d449cabeb7a.jpg)

**Comment by PreLeyZero** [comment]
use an insulted pipe isntead of a regular one for the transport of liquid nitdrogen and liquid oxygen as well as for super hot plasmas.

**Comment by xaviershay** [comment]
ahhhh thank you!

(Still feels like a weird interaction though? Putting computer data(?) in a pipe destroys the pipe, which confused me for a bit but ultimately led me to the solution of using computer cable. Though in hindsight not sure why that was more obvious to me than this. Maybe I haven't researched insulated pipe yet? Will have to check...)
