### ISSUE TITLE
Duplicating the character

### ISSUE THREAD

**Issue by NotSoFastBaby** [PreLeyZero/exotic-industries#46]
After you left click a drone while its being operated you can exit the drone (default button 'Enter' i believe) creating a copy of your character. If you create a copy of yourself on gaia then click exit, drone disappears, then if you click reset, game crashes.

**Comment by PreLeyZero** [comment]
i guess you are playing with remote configuration mod?
If so update it when possible, thats an issue with the permission system of EI and remote config. Ill work on a fix
