### ISSUE TITLE
Recipe Book 4 compatibility

### ISSUE THREAD

**Issue by raiguard** [PreLeyZero/exotic-industries#53]
I am aiming to finish and release Recipe Book 4 at the end of the month. RB4 provides a data-stage API for overriding various properties and behaviors. The API is exposed via a `recipe_book` global variable. You can read it over [here](<https://github.com/raiguard/RecipeBook/blob/v4.0/prototypes/overrides-api.lua>) and example usage [here](<https://github.com/raiguard/RecipeBook/blob/v4.0/prototypes/vanilla-overrides.lua>).

If you wish to test I can provide a prerelease zip of Recipe Book and flib, or you can clone the repositories.

EI mostly behaves pretty well, but the custom rocket scripting means certain things aren't ever marked as researched. I will have to add a runtime API to allow EI to mark things as unlocked, I'll let you know when that is complete.

**Comment by DaleStan** [comment]
Has this happened? I have a similar problem in [YAFC](https://github.com/shpaass/yafc-ce), and I'd prefer to hook into something that already exists, if possible.

**Comment by raiguard** [comment]
With the impending release of Factorio 2.0 with the Factoriopedia, I unfortunately canceled RB4. Recipe Book will not be updated to 2.0.
