### ISSUE TITLE
Provide API to configure the allowed surfaces for the Gaia buildings

### ISSUE THREAD

**Issue by pdegand** [PreLeyZero/exotic-industries#56]
Would it be possible to remove the hardcoded `gaia` surface name and instead use a global list of allowed surface names (with `gaia` as a default allowed surface) ? A remote interface would be added to provide the ability for other mods to add new surface names into the list of allowed surfaces in EI.

A concret use case would be to have a compatibility mod for both EI and Editor Extensions to automatically add the EE test lab surface name to the allowed surfaces in EI to be able to build Gaia buildings inside the lab.

**Comment by PreLeyZero** [comment]
possible via new interface :)
