### ISSUE TITLE
[Bug] Crash when opening rocket silo placed by robot ( + suggested 1 line fix)

### ISSUE THREAD

**Issue by chdcl** [PreLeyZero/exotic-industries#62]
When a rocket silo is placed by a robot in my game, the recipe is automatically set to "rocket-part". Calling get_destination on this entity returns "t", which results in a crash upon clicking the silo.

This bug occurs with exclusively mods from the official mod pack enabled. Placing the rocket silo manually works fine.

Luckily the bug can easily be fixed by improving the string matching in the function `model.get_destination(entity)` in `scripts\control\planet_exploration.lua`

`local destination = string.match(recipe.name, "^ei_rocket:(.*)") or "nauvis-orbit"`

**Comment by PreLeyZero** [comment]
Thanks a lot. Will be in the next version alongside the K2 compat.
