### ISSUE TITLE
Crash on knowledge scan out of order

### ISSUE THREAD

**Issue by overloader7** [PreLeyZero/exotic-industries#63]
Scanning before building knowledge console at least once causes crash because the knowledge system is not initialised on player before then (crash on indexing knowledge by player faction on `line 703 in knowledge_system.lua`). Its probably better to move the `enable_knowledge` call to whenever the appropriate research is completed, or at least add a warning before its fixed

**Comment by bengardner** [comment]
I hit this, too.
Adding this near the top of `model.scan_artifact()` may also be enough to prevent the crash.
```lua
model.enable_knowledge(player)
```

**Comment by PreLeyZero** [comment]
fixed in next version :)
