### ISSUE TITLE
Add whitelist to selection tool ei_scanner

### ISSUE THREAD

**Issue by bengardner** [PreLeyZero/exotic-industries#65]
It is a bit confusing to to see the knowledge scanner select stuff it can't scan.
The selection tools can have an entity whitelist added. That helps.

It appears the easiest place to set the filters in in the `data-final-fixes` stage. All prototypes can be scanned at that stage looking for matches.

It might be best to move `model.scanner_values` from `scripts/control/knowledge_system.lua` to a file that can be included in both the `data` and `control` phases, such as `lib/data.lua`.

Once the entity list is collected:
```lua
local ei_scanner = data.raw['selection-tool']['ei_scanner']
ei_scanner.entity_filter_mode = "whitelist"
ei_scanner.entity_filters = entity_filters
```

I'll attach a pull request to illustrate.

**Comment by bengardner** [comment]
Added pull request #66 as a possible implementation.

**Comment by PreLeyZero** [comment]
thanks a lot - looks better ingame :)
