### ISSUE TITLE
Disabling the K2 setting "More Realistic Weapons" causes EI to break.

### ISSUE THREAD

**Issue by billbo99** [PreLeyZero/exotic-industries#69]
Disabling the K2 setting "More Realistic Weapons" causes EI to break on startup.   I disable this setting as its suggest that it can cause problems on multi-player maps.

![image 1](https://github.com/PreLeyZero/exotic-industries/assets/17733206/7e6de994-ae62-40d7-b157-e30164bb6652)

![image 1](https://github.com/PreLeyZero/exotic-industries/assets/17733206/2eeb9445-7a69-4346-a9e2-669290c000dc)

**Comment by PreLeyZero** [comment]
Ill write a patch for that :)
