### ISSUE TITLE
Crash on start with Krastorio 2 installed

### ISSUE THREAD

**Issue by mindbound** [PreLeyZero/exotic-industries#71]
I'm getting the following error on start when both Exotic Industries and Krastorio 2 are installed and enabled:

```
   2.908 Error ModManager.cpp:1625: Failed to load mod "exotic-industries": ...tries__/scripts/data-final-updates/krastorio_patches.lua:2146: attempt to index field 'kr-electric-offshore-pump' (a nil value)
stack traceback:
        ...tries__/scripts/data-final-updates/krastorio_patches.lua:2146: in main chunk
        [C]: in function 'require'
        __exotic-industries__/data-final-fixes.lua:13: in main chunk
```

Mod list: [mod-list.json](https://github.com/PreLeyZero/exotic-industries/files/15334327/mod-list.json)

**Comment by PreLeyZero** [comment]
Looks like an issue with AAI.

When using the SE compat mod and this still happens maybe reach out in my discord to Eliont.
